version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports: ['9200:9200']
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    ports:
    - '9600:9600'  # Puerto para la API de monitoreo de Logstash
    - '5000:5000'  # Puerto para recibir los logs desde el SocketAppender
    depends_on: ['elasticsearch']
    volumes:
      - './etc/logstash/pipeline:/usr/share/logstash/pipeline'
      - './var/logs:/logs'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports: ['5601:5601']
    depends_on:
      - 'elasticsearch'